package JNA_SCIP;

public enum SCIP_PROPTIMING {
	SCIP_PROPTIMING_NEVER, //0x0
	SCIP_PROPTIMING_BEFORELP, //0x1
	SCIP_PROPTIMING_DURINGLPLOOP, //0x2
	SCIP_PROPTIMING_BEFORELP_DURINGLPLOOP, //0x1|0x2
	SCIP_PROPTIMING_AFTERLPLOOP, //0x4
	SCIP_PROPTIMING_BEFORELP_AFTERLPLOOP, //0x1|0x4
	SCIP_PROPTIMING_DURINGLPLOOP_AFTERLPLOOP, //0x2|0x4
	SCIP_PROPTIMING_BEFORELP_DURINGLPLOOP_AFTERLPLOOP, //0x1|0x2|0x4
	SCIP_PROPTIMING_AFTERLPNODE, //0x8
	SCIP_PROPTIMING_BEFORELP_AFTERLPNODE, //0x1|0x8
	SCIP_PROPTIMING_DURINGLPLOOP_AFTERLPNODE, //0x2|0x8
	SCIP_PROPTIMING_BEFORELP_DURINGLPLOOP_AFTERLPNODE, //0x1|0x2|0x8
	SCIP_PROPTIMING_AFTERLPLOOP_AFTERLPNODE, //0x4|0x8
	SCIP_PROPTIMING_BEFORELP_AFTERLPLOOP_AFTERLPNODE, //0x1|0x4|0x8
	SCIP_PROPTIMING_DURINGLPLOOP_AFTERLPLOOP_AFTERLPNODE, //0x2|0x4|0x8
	SCIP_PROPTIMING_ALWAYS; //all four
}
