package JNA_SCIP;

/* type_var.h */
public enum SCIP_VARSTATUS {
   SCIP_VARSTATUS_ORIGINAL ,
   SCIP_VARSTATUS_LOOSE,
   SCIP_VARSTATUS_COLUMN,
   SCIP_VARSTATUS_FIXED,
   SCIP_VARSTATUS_AGGREGATED,
   SCIP_VARSTATUS_MULTAGGR,
   SCIP_VARSTATUS_NEGATED,
}