package JNA_SCIP;

public enum SCIP_PARAMEMPHASIS {
	SCIP_PARAMEMPHASIS_DEFAULT,
	SCIP_PARAMEMPHASIS_CPSOLVER,
    SCIP_PARAMEMPHASIS_EASYCIP,
    SCIP_PARAMEMPHASIS_FEASIBILITY,
    SCIP_PARAMEMPHASIS_HARDLP,
    SCIP_PARAMEMPHASIS_OPTIMALITY,
    SCIP_PARAMEMPHASIS_COUNTER,
    SCIP_PARAMEMPHASIS_PHASEFEAS,
    SCIP_PARAMEMPHASIS_PHASEIMPROVE,
    SCIP_PARAMEMPHASIS_PHASEPROOF,
    SCIP_PARAMEMPHASIS_NUMERICS,
    SCIP_PARAMEMPHASIS_BENCHMARK
}