package JNA_SCIP;

/* type_set.h */
public enum SCIP_STAGE
{
   SCIP_STAGE_INIT,
   SCIP_STAGE_PROBLEM,
   SCIP_STAGE_TRANSFORMING,
   SCIP_STAGE_TRANSFORMED,
   SCIP_STAGE_INITPRESOLVE,
   SCIP_STAGE_PRESOLVING,
   SCIP_STAGE_EXITPRESOLVE,
   SCIP_STAGE_PRESOLVED,
   SCIP_STAGE_INITSOLVE,
   SCIP_STAGE_SOLVING,
   SCIP_STAGE_SOLVED,
   SCIP_STAGE_EXITSOLVE,
   SCIP_STAGE_FREETRANS,
   SCIP_STAGE_FREE
}